package com.dcits.test.mail.page;

import com.dcits.yi.ui.element.BasePage;
import com.dcits.yi.ui.element.PageElement;

/**
 * This PageModel is generated by MasterYIUITest
 * @author xuwangcheng14@163.com
 */

public class MailLogoutPage extends BasePage {
	
	public PageElement 重新登录按钮;
	
	/**
	 * 验证是否成功登出
	 * @throws Exception
	 */
	public void verifyLogout() throws Exception {
		Assert(getTitle().equals("网易邮箱 - 您已成功退出邮箱"), "当前标题不是[网易邮箱 - 您已成功退出邮箱]，可能没有退出成功!");
	}
	/**
	 * 重新登录
	 */
	public void reLogin() {
		重新登录按钮.click();
	}
}