package com.dcits.test.mail.page;

import org.openqa.selenium.Keys;

import com.dcits.yi.ui.element.BasePage;
import com.dcits.yi.ui.element.PageElement;

/**
 * This PageModel is generated by MasterYIUITest
 * @author xuwangcheng14@163.com
 */

public class MailPage extends BasePage {
	
	public PageElement 用户标签;	
	public PageElement 写信按钮;	
	public PageElement 收信人;	
	public PageElement 收信人地址;	
	public PageElement 发信按钮;	
	public PageElement 发送成功确认按钮;	
	public PageElement 收信按钮;	
	public PageElement 邮件搜索框;	
	public PageElement 收信列表链接;	
	public PageElement 邮件搜索按钮;	
	public PageElement 回复按钮;	
	public PageElement 邮件内容输入框;	
	public PageElement 登出按钮;	
	
	/**
	 * 验证登录是否成功
	 * @param loginEmail
	 * @throws Exception 
	 */
	public void verifyLogin(String loginEmail) throws Exception {
		Assert(用户标签.getText().equals(loginEmail), "实际结果为{}， 与预期结果{}不一致，验证失败!", 用户标签.getText(), loginEmail);
	}
	
	/**
	 * 发送邮件
	 * @param receiveEmail 收件人地址
	 * @param title 邮件标题/主题
	 * @param sendContent 邮件内容
	 */
	public void sendEmail(String receiveEmail, String title, String sendContent) {
		写信按钮.click();
		收信人.click();
		收信人地址.sendKeys(receiveEmail, false);
		邮件内容输入框.sendKeys(sendContent, false);
		发信按钮.click();
		发送成功确认按钮.click();	
	}
	
	/**
	 * 收信
	 */
	public void reveiceEmail(String sendEmail) {
		收信按钮.click();
		邮件搜索框.click();
		邮件搜索框.sendKeys(sendEmail, true);
		邮件搜索框.sendKeys(Keys.ENTER + "");
		收信列表链接.click();
	}
	
	/**
	 * 回复邮件
	 */
	public void replyEmail(String sendContent) {
		回复按钮.click();
		邮件内容输入框.sendKeys(sendContent);
		发信按钮.click();
	}
	
	/**
	 * 登出
	 */
	public void logout() {
		登出按钮.click();
	}
}